### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [Hackuarium/libino#1]
You might need to have another look at the wireReadInt() function in the file "libino/hack/WireMaster.h", the variable is 'i' is not incremented.
There is no need to do a `while(Wire.available()`.
You may do this:
```
int wireReadInt(uint8_t address) {
  Wire.requestFrom(address, (uint8_t)2);
  if(Wire.available() != 2) {
    return ERROR_VALUE;
  }

  int data = Wire.read();  // high byte is received first
  data <<= 8;
  data |= Wire.read();

  return data;
}
```

If the low byte is received first, you can do this instead:
```
  int data = Wire.read();  // low byte is received first
  data |= Wire.read() << 8;
```

**Comment by lpatiny** [comment]
Many thanks for you comments. My code was indeed completely wrong because I didn't even give back an error if there was no byte read.
